baseURL = "https://seanmoon80.github.io/"
languageCode = "en-us"
title = "Playground"
theme = "hugo-theme-minos"
staticDir = ["static"]

[menu]
  [[menu.main]]
    identifier = 'posts'
    name = "Posts"
    url = "/posts/"
